# Generated by Django 5.2.11 on 2026-03-02 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FacebookSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cookies", models.JSONField()),
                ("fb_dtsg", models.CharField(max_length=500)),
                ("lsd", models.CharField(max_length=200)),
                ("doc_id_members", models.CharField(max_length=50)),
                ("doc_id_hovercard", models.CharField(max_length=50)),
                ("variables_members", models.JSONField(default=dict)),
                ("payload_params", models.JSONField(default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="FacebookUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("facebook_id", models.CharField(max_length=50, unique=True)),
                (
                    "enrich_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("done", "Done"),
                            ("closed", "Closed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("enrich_attempts", models.PositiveSmallIntegerField(default=0)),
                (
                    "avatar_path",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("scraped_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("enriched_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(blank=True, max_length=500, null=True)),
                ("url", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "avatar_url",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                ("bio", models.TextField(blank=True, null=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("join_date", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "invite_status",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("user_type", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "friendship_status",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "group_member_url",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("username", models.CharField(blank=True, max_length=200, null=True)),
                ("is_memorialized", models.BooleanField(default=False)),
                (
                    "profile_url",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("short_name", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True, db_index=True, max_length=50, null=True
                    ),
                ),
                ("context_items", models.JSONField(blank=True, default=list)),
                ("mutual_friends_count", models.IntegerField(blank=True, null=True)),
                ("mutual_friends_sample", models.JSONField(blank=True, default=list)),
            ],
            options={
                "ordering": ["scraped_at"],
            },
        ),
        migrations.CreateModel(
            name="ParserState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("group_id", models.CharField(max_length=50, unique=True)),
                ("next_cursor", models.TextField(blank=True, null=True)),
                ("is_finished", models.BooleanField(default=False)),
            ],
        ),
    ]
