# Generated by Django 4.2.28 on 2026-02-24 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FacebookSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cookies", models.JSONField()),
                ("fb_dtsg", models.CharField(max_length=500)),
                ("lsd", models.CharField(max_length=200)),
                ("doc_id_members", models.CharField(max_length=50)),
                ("doc_id_hovercard", models.CharField(max_length=50)),
                ("variables_members", models.JSONField(default=dict)),
                ("payload_params", models.JSONField(default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="FacebookUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("facebook_id", models.CharField(max_length=50, unique=True)),
                (
                    "enrich_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("done", "Done"),
                            ("closed", "Closed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("enrich_attempts", models.PositiveSmallIntegerField(default=0)),
                (
                    "avatar_path",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("scraped_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("enriched_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["scraped_at"],
            },
        ),
        migrations.CreateModel(
            name="ParserState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("group_id", models.CharField(max_length=50, unique=True)),
                ("next_cursor", models.TextField(blank=True, null=True)),
                ("is_finished", models.BooleanField(default=False)),
            ],
        ),
    ]
